config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }

  resources :books do
  	resources :comments, controller: 'book_comments'
	
  	collection do
  	  get :about
  	  post :bulk_selectgroup
  	end

    member do
      post :collection
      post :like
      post :subscribe
      post :schedule
    end
  end



  resources :users 
  resources :friendships

  namespace :admin do
    resources :books
    resources :groups
    resources :users
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root "books#index"
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable,
         :omniauthable, :omniauth_providers => [:facebook]

  has_many :owner_books , :class_name => "Book" , :foreign_key => "user_id", :dependent => :destroy
  has_many :comments , :dependent => :destroy

  has_many :user_bookships
  has_many :collected_books, through: :user_bookships, :source => :book


  has_many :likes, :dependent => :destroy
  has_many :liked_books, through: :likes, :source => :book

  has_many :subscribes, dependent: :destroy
  has_many :subscribed_books, through: :subscribes, source: :book

  has_many :friendships
  has_many :friends, ->{ where( "friendships.status" => "confirmed") }, :through => :friendships

  has_many :inverse_friendships, :class_name => "Friendship", :foreign_key => "friend_id"
  has_many :inverse_friends, ->{ where( "friendships.status" => "confirmed") }, :through => :inverse_friendships, :source => "user"
  
  def short_name
  	self.email.split("@").first
  end

  def liked_book?(book)
    self.liked_books.include?(book)
  end

  def self.from_facebook_omniauth(auth)
     # Case 1: Find existing user by facebook uid
     user = User.find_by_fb_uid( auth.uid )
     if user
        user.fb_token = auth.credentials.token
        #user.fb_raw_data = auth
        user.save!
       return user
     end

     # Case 2: Find existing user by email
     existing_user = User.find_by_email( auth.info.email )
     if existing_user
       existing_user.fb_uid = auth.uid
       existing_user.fb_token = auth.credentials.token
       #existing_user.fb_raw_data = auth
       existing_user.save!
       return existing_user
     end

     # Case 3: Create new password
     user = User.new
     user.fb_uid = auth.uid
     user.fb_token = auth.credentials.token
     user.email = auth.info.email
     user.password = Devise.friendly_token[0,20]
     #user.fb_raw_data = auth
     user.save!
     return user
   end

  def all_friends
    (friends + inverse_friends).uniq
  end

  def find_friendship(user)
    friendships.where( :friend => user ).first ||
    user.friendships.where( :friend => self ).first
  end

  def is_friend?(user)
    all_friends.include?(user)
  end

  def pending_friendship?(user)
    self.friendships.pending.where( :friend => user ).exists?
  end

  def inverse_pending_friendship?(user)
    user.friendships.pending.where( :friend => self ).exists?
  end

  def ignored_friendship?(user)
    self.friendships.ignored.where( :friend => user ).exists?
  end

  def inverse_ignored_friendship?(user)
    user.friendships.ignored.where( :friend => self ).exists?
  end
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < ApplicationController
	before_action :is_admin
	before_action :authenticate_user!

	def index
		if params[:pass].present?
			@user = User.find(params[:pass])
			@user.update(role: "admin")
		end

		@users = User.all
	end

	def edit
		@user = User.find(params[:id])
	end

	def update
		@user = User.find(params[:id])
		@user.update(strong_params)
		redirect_to admin_users_path
	end

	def destroy
		@user = User.find(params[:id])
		@user.destroy
		redirect_to admin_users_path
	end




	private

	def strong_params
		params.require(:user).permit(:introduction, :role)
	end

	def is_admin
      unless  current_user.role == "admin"
          redirect_to root_path
          return
      end
    end 
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  def facebook
    # You need to implement the method below in your model (e.g. app/models/user.rb)
    @user = User.from_facebook_omniauth(request.env["omniauth.auth"])

    if @user.persisted?
      sign_in_and_redirect @user, :event => :authentication #this will throw if @user is not activated
      set_flash_message(:notice, :success, :kind => "Facebook") if is_navigational_format?
    else
      session["devise.facebook_data"] = request.env["omniauth.auth"]
      redirect_to new_user_registration_url
    end
  end

  def failure
    redirect_to root_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	
	before_action :set_before, except: [:index, :new, :create]

	def index
		
	end

	def show
		@publicbooks = @user.owner_books.where(is_public: true)
		@draftbooks = @user.owner_books.where(is_public: false)
		@publiccomments = @user.comments.where(is_public: true)
		@draftcomments = @user.comments.where(is_public: false)
	end


	def edit
	end

	def update
		@user.update(set_params)
		redirect to user_path(@user)
	end
 
	private

	def set_before
		@user = User.find(params[:id])
	end

	def set_params
		params.require(:user).permit(:role)
	end
end

app/helpers/admin/users_helper.rb
module Admin::UsersHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/show.html.erb
<h3>This is <%= @user.short_name %>'s profile</h3>
<h3>introduction: <%= @user.introduction%></h3>
<table class="table table-striped">
	<thead>
		<tr>
			<th>Public Books</th>
		</tr>
	</thead>
	<tbody>		
			<% @publicbooks.each do |b| %>
			<tr>
				<td><%= b.name%></td>
			</tr>
			<%end%>
	</tbody>

</table>
<div class="container col-md-6">
	<table class="table table-striped">
		<thead>
			<tr>
				<th>Collection</th>
			</tr>
		</thead>
		<tbody>
				<% @user.collected_books.each do |b| %>
				<tr>
					<td>
						<%= Book.find(b).name%>
					</td>
				<%end%>
				</tr>
		</tbody>

	</table>
</div>
<div class="container col-md-6">
	<table class="table table-striped">
		<thead>
			<tr>
				<th>Like</th>
			</tr>
		</thead>
		<tbody>
				<% @user.liked_books.each do |b|%>
				<tr>
					<td>
						<%= Book.find(b).name%>
					</td>
				<%end%>
				</tr>
		</tbody>
	</table>
</div>

<table class="table table-striped">
	<thead>
		<tr>
			<th>Books</th>
			<th>Comments from <%= @user.last_name%></th>
		</tr>
	</thead>
	<tbody>		
			<% @publiccomments.each do |b| %>
			<tr>
				<td><%= b.book.name%></td>
				<td><%= b.description%></td>
			</tr>
			<%end%>
	</tbody>
</table>
<%if current_user && current_user == @user%>
	<table class="table table-striped">
		<thead>
			<tr>
				<th>Books in draft</th>
				<th>Edit</th>
			</tr>
		</thead>
		<tbody>		
				<% @draftbooks.each do |b| %>
				<tr>
					<td><%= b.name%></td>
					<td><%= link_to "Edit", edit_book_path(b)%></td>
				</tr>
				<%end%>
		</tbody>
	</table>

	<table class="table table-striped">
		<thead>
			<tr>
				<th>Books</th>
				<th>Comments in draft</th>
				<th>Edit</th>
			</tr>
		</thead>
		<tbody>		
				<% @draftcomments.each do |c| %>
				<tr>
					<td><%= c.book.name%></td>
					<td><%= c.description%></td>
					<td><%= link_to "Edit", book_path(c.book, eid: c.id)%></td>
				</tr>
				<%end%>
		</tbody>
	</table>
<%end%>

<% if @user != current_user %>
  <p>Status:

    <% if current_user.is_friend?(@user) %>
      已經是朋友
    <% elsif current_user.pending_friendship?(@user) %>
      等待對方確認 [Remove]
    <% elsif current_user.inverse_pending_friendship?(@user) %>
      交友邀請中 [Confirm] [Ignore]
    <% elsif current_user.ignored_friendship?(@user) %>
      等待對方確認 [Remove] <- 安慰版!!
    <% elsif current_user.inverse_ignored_friendship?(@user) %>
      已被我忽略 [Confirm]
    <% else %>
      目前沒關係 <%= link_to "Request", friendships_path( :friend_id => @user), :method => :post %>
    <% end %>

  </p>
<% end %>

<h2>All friend list</h2>
<ul>
  <% @user.all_friends.each do |f| %>
    <li>
      <%= link_to f.name, user_path(f) %>

      <% if current_user == @user %>
        <% fs = current_user.find_friendship(f) %>
        <%= link_to "Remove", friendship_path(fs), :method => :delete, :data => { :confirm => "Are you sure?" } %>
      <% end %>

    </li>
  <% end %>
</ul>

<% if @user == current_user %>

  <h2>Request list</h2>
    <ul>
    <% @user.friendships.pending.each do |f| %>
     <li>
        <%= link_to f.friend.name, user_path(f.friend) %>
        <%= link_to "Remove", friendship_path(f), :method => :delete, :data => { :confirm => "Are you sure?" } %>
      </li>
    <% end %>
    </ul>


  <h2>Pending list</h2>

    <ul>
    <% @user.inverse_friendships.pending.each do |f| %>
     <li>
        <%= link_to f.user.name, user_path(f.user) %>
        <%= link_to "Confirm", friendship_path(f, :status => :confirmed), :method => :patch %>

        <%= link_to "Ignore", friendship_path(f, :status => :ignored), :method => :patch %>
      </li>
    <% end %>
    </ul>

<% end %>