config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }

  resources :books do
  	resources :comments, controller: 'book_comments'
	
  	collection do
  	  get :about
  	  post :bulk_selectgroup
  	end

    member do
      post :collection
      post :like
      post :subscribe
      post :schedule
    end
  end



  resources :users 
  resources :friendships

  namespace :admin do
    resources :books
    resources :groups
    resources :users
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root "books#index"
end

app/models/book.rb
class Book < ApplicationRecord
	validates_presence_of :name

	belongs_to :user, optional: true
	belongs_to :category, optional: true

	has_many :comments, :dependent => :destroy
	has_many :book_groupships, :dependent => :destroy
	has_many :groups, through: :book_groupships

	has_many :user_bookships
	has_many :users, through: :user_bookships

	has_many :likes, :dependent => :destroy
	has_many :likers, :through => :likes, :source => :user

	has_many :subscribes, dependent: :destroy
	has_many :subscribers, through: :subscribes, source: :user

	has_attached_file :logo, styles: { medium: "300x300>", thumb: "100x100>" }, default_url: "/images/:style/missing.png"
	validates_attachment_content_type :logo, content_type: /\Aimage\/.*\z/

	has_many :taggings, dependent: :destroy
	has_many :tags, through: :taggings
	
	def user_uniq
		list=[]
		self.comments.each do |comment|
			list << comment.user.short_name
		end
			list = list.uniq
	end

	def tag_list
		self.tags.map{ |tag| tag.name}
	end

	def tag_list=(arr)
			ids = arr.map do |tag_name|
			  tag_name = tag_name.strip.downcase
			  tag = Tag.find_by_name( tag_name ) || Tag.create( :name => tag_name )
			  tag.id
			end
		self.tag_ids = ids
	end
end

app/controllers/admin/books_controller.rb
class Admin::BooksController < ApplicationController

    before_action :authenticate_user!
    before_action :is_admin
    layout "admin"

    def index
    	@books = Book.all
    	@users = User.all
    end

    protected

    def is_admin
      unless  current_user.role == "admin"
          redirect_to root_path
          return
      end
    end    


end

app/controllers/books_controller.rb
class BooksController < ApplicationController

	before_action :authenticate_user!, except: [:index, :show]
	before_action :find_book, only: [:show, :edit, :update, :collection, :like, :subscribe, :destroy]
	before_action :security, only: [:edit, :update, :destroy]

	def index

		if params[:commit].present? && params[:commit] != "All"
			@books = Group.find_by_name(params[:commit]).books
		else
			@books = Book.all
		end
			# if params[:commit] == "Comedy"
			#   @books = @books.where('groups.id' => 1)
			# elsif params[:commit] == "Tragedy"
			# 	@books = @books.where('groups.id' => 2)
			# elsif params[:commit] == "NObody"n 
			# 	@books = @books.where('groups.id' => 3)
			# end
		# end
		@books = @books.where(is_public: true).where("onshelf_day <= ?", Time.now).includes(:groups)


		
			# if   == "update_time"
				# sort_by = "#{params[:order]} DESC"
			# elsif params[:order] == "ids"
			# 	sort_by = 'id ASC'
			# elsif params[:order] == "comments"
			# 	sort_by = 'comment_number DESC'
			# elsif params[:order] == "views"
			# 	sort_by = 'views DESC'
			# end

		# if params[:order].present?
		# 	@books = @books.order("#{params[:order]} DESC")	
		# else
		# 	@books = @books.order("id DESC")
		# end

		params[:order] ||= 'id'
		@books = @books.order("#{params[:order]} DESC")	

		@books = Tag.find_by_name(params[:tag]).books  if params[:tag].present?
		@books = @books.page( params[:page] ).per(10)



	end

	def show
		if params[:eid].present?
			@comment = @book.comments.find(params[:eid])
		else
			@comment = Comment.new
		end
		@book.views += 1
		# @user = current_user
		@book.save
		@comments = @book.comments.where(is_public: true)
		@comments = @comments.page( params[:page] ).per(5)
	end

	def about
		@users = User.all
		@books = Book.all		
		@comments = Comment.all
	end

	def new
		@book = Book.new
	end

	def create

		@book = Book.new(set_params)
		@book.user = current_user
		@book.comment_number = 0
		@book.views = 0
		
		if params[:commit] == "Create Book" 
			if @book.save
				@book.update(is_public: true) 
				flash[:notice] = "Add file success"
			    redirect_to book_path(@book, page: params[:page])
			else
				flash[:alert] = "Add fail"
				render 'edit'
			end
		elsif params[:commit] == "draft"
			if @book.save
				flash[:notice] = "Add file into draft"
			    redirect_to book_path(@book, page: params[:page])
			else
				flash[:alert] = "Add fail"
				render 'edit'
			end
		elsif params[:commit] == "schedule"
			if @book.save
				@book.update(is_public: true)
				flash[:notice] = "This file will publish on #{@book.onshelf_day}"
			    redirect_to book_path(@book, page: params[:page])
			else
				flash[:alert] = "Add fail"
				render 'edit'
			end
		end
	end

	def edit
	end

	def update
			
		if params[:remove_img] == "1"
			@book.logo = nil
		end
		if params[:commit] == "Update Book"
			if @book.update(set_params)
				@book.update(is_public: true) 
				flash[:notice] = "Editted file success"
				redirect_to book_path(@book, page: params[:page])
			else
				flash[:alert] = "Editted fail"
				render 'edit'
			end
		elsif params[:commit] == "draft"
			if @book.update(set_params)
				flash[:notice] = "Editted file into draft"
				redirect_to book_path(@book, page: params[:page])
			else
				flash[:alert] = "Editted fail"
				render 'edit'
			end
		elsif params[:commit] == "schedule"
			if @book.update(set_params)
				@book.update(is_public: true)
				flash[:notice] = "This file will publish on #{params[:onshelf_day]}"
			    redirect_to book_path(@book, page: params[:page])
			else
				flash[:alert] = "Add fail"
				render 'edit'
			end
		end
	end

	def collection
		# @userbookship = UserBookship.create(
		# 	:user_id => current_user.id,
		# 	:book_id => @book.id
		# 	)
		if !current_user.collected_books.exists?(@book)
			current_user.collected_books << @book
			respond_to do |format|
				format.html {redirect_to user_path(current_user)}
				format.js
				end
		else
			flash[:alert] = "This book is already collected."
		end

	end

	def like
		if current_user.liked_book?(@book)
			current_user.liked_books.delete(@book)
		else
			current_user.liked_books << @book
		end

		respond_to do |format|
		format.html {redirect_to book_path(@book)}
		format.js
		end
	end

	def subscribe
		if current_user.subscribed_books.exists?(@book.id)
			current_user.subscribed_books.delete(@book)
		else
			current_user.subscribed_books << @book
		end


		respond_to do |format|
		format.html {redirect_to books_path}
		format.js
		end
	end

	def destroy
		@book.destroy
		
		respond_to do |format|
			format.html {redirect_to books_path(page: params[:page])}
			format.js
		end
		
	end
	private

	def set_params
		params.require(:book).permit(:name, :description, :user_id, :comment_number, :category_id, :is_public, :logo, 
									 :onshelf_day, :tag_list, group_ids: [], book_ids: [], tag_list: [])
	end

	def find_book
		@book = Book.find(params[:id])
	end

	def security
		if current_user != @book.user && current_user.role != "admin"
			flash[:alert] = "You are not allowed."
			redirect_to books_path
		end
	end
end

app/helpers/admin/books_helper.rb
module Admin::BooksHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/views/books/_form.html.erb
<div class="form-group">
	<%= b.label :name%>
	<%= b.text_field :name%>
</div>
<div class="form-group">
	<%= b.file_field :logo%>
	<%if @book.logo.exists?%>
		<%= b.label "Remove photo"%>
		<%= check_box_tag "remove_img", "1"%>
	<%end%>
</div>
<div class="form-group">
	<%= b.label :description%>
	<%= b.text_area :description%>
</div>
<!--  <div class="form-group">
    <%= b.label :onshelf_day, "On shelf" %>
    <%= b.text_field :onshelf_day%>
</div> -->
<div class="form-group col-xs-3">
	<%= b.label :tag_list %>
 	<%= b.select :tag_list , Tag.all.map{ |x| [x.name, x.name] }, {}, :multiple => true%>
</div>
<!-- <div class="form-group">
	<%= b.select :tag_ids, Tag.all.map{ |x| [x.name, x.id] }, {}, :multiple => true %>
</div> -->
<!-- <div class="form-group">
	<%= b.collection_check_boxes(:group_ids, Group.all, :id, :name)%>
</div> -->

<div class="form-group submit">
	<%= b.submit "schedule"%>
	<%= b.label :onshelf_day, "On shelf" %>
    <%= b.text_field :onshelf_day%>
</div>

<div class="form-group submit">
	<%= b.submit "draft"%>
	<%= b.submit%>
</div>



<script>
   $("#book_onshelf_day").datepicker({
     format: "yyyy-mm-dd"
   });

   $("#book_tag_list").select2({
     tags: true,
     multiple: true 
     // tags: <%= raw( Tag.all.map{ |x| x.name }.to_json ) %>,
     // theme: "bootstrap",
     // tags: gon.tags,
     // tokenSeparators: [',', ' ']
   });
</script>

app/views/books/_like.html.erb
	<% if current_user.liked_book?(@book)%>
		<%= button_to "Unlike", like_book_path(@book), remote: true%>
		<h2><%= @book.likers.count%> Likes</h2>
		<h4>who like this book?</h4>
		<% @book.likers.each do |l|%>
			<p><%= l.short_name%></p>
		<%end%>
	<% else %>
		<%= button_to "Like", like_book_path(@book), remote: true%>
		<h2><%= @book.likers.count%> Likes</h2>
		<h4>who like this book?</h4>
		<% @book.likers.each do |l|%>
			<p><%= l.short_name%></p>
		<%end%>
	<%end%>

app/views/books/_schedule.html.erb
<div class="form-group submit">
	<%= b.submit "schedule"%>
	<%= b.label :onshelf_day, "On shelf" %>
    <%= b.text_field :onshelf_day%>
</div>

app/views/books/about.html.erb
<h1>The amount of users : <%= @users.count%></h1>
<h1>The amount of titles : <%= @books.count%></h1>
<h1>The amount of comments : <%= @comments.count%></h1>

app/views/books/collection.js.erb
$(".collect").html("<h3>Book collected</h3>")

app/views/books/destroy.js.erb
// $(".delete").closest("tr").css({"color": "red", "border": "2px solid red"});
$('.delete').on('ajax:success', function() {  
        $(this).closest('tr').fadeOut();
});  

app/views/books/edit.html.erb
<%= form_for @book do |b|%>
	<%= render partial: 'form', locals: {b: b, book: @book}%>
<%end%>

app/views/books/index.html.erb
<%= form_tag books_path, :method => :get do%>
	<% Group.all.each do |g|%>
		<%= submit_tag g.name%>
	<%end%>
	<%= submit_tag "All"%>
<%end%>

<%= link_to 'Sort by default', books_path(:order => 'id', :commit => params[:commit])%>

<table class="table table-striped">
	<thead>
		<tr>
			<th>Logo</th>
			<th>Book name</th>
			<th>On shelf</th>
			<th>Author</th>
			<th><%= link_to "Comment number", books_path(:order => 'comment_number', :commit => params[:commit])%></th>
			<th>Comments from</th>
			<th><%= link_to "Views", books_path(:order => 'views', :commit => params[:commit])%></th>
			<th><%= link_to "Update time", books_path(:order => 'updated_at', :commit => params[:commit])%></th>
			<th>Tag</th>
			<%if current_user%>
				<th>Subscribe</th>
				<th>Edit</th>
				<th>Delete</th>
			<%end%>
		</tr>
	</thead>
	<tbody>
		<tr>
		<% @books.each do |book|%>
			<%if book.logo.exists?%>
				<td><%= image_tag(book.logo.url(:thumb) )%></td>
			<%else%>
				<td>None</td>
			<%end%>
			<td><%= link_to book.name, book_path(book, page: params[:page])%></td>
			<td><%= book.onshelf_day%></td>
			<td><%= link_to book.user.short_name, user_path(book.user)%></td>
			<td><%= book.comment_number%></td>
			<td>
				<% book.user_uniq.each do |u| %>
				<p><%= u %></p>
				<%end%>
			</td>
			<td><%= book.views%></td>
			<td><%= book.updated_at.strftime("%F %H:%M")%></td>
			<td>
				<% book.tags.each do |t|%>
					<%= link_to t.name, books_path(tag: t.name)%>
				<% end %>
			</td>
			<%if current_user%>
				<%if current_user.subscribed_books.exists?(book.id)%>
					<td><button class="subs"><%= link_to "Unsubscribe",subscribe_book_path(book), method: :post,remote: true%></button></td>
				<%else%>
					<td><button class="subs"><%= link_to "Subscribe", subscribe_book_path(book), method: :post,remote: true%></button></td>
				<%end%>
			<%end%>
			<%if current_user && current_user == book.user || current_user.try(:role) == "admin"%>
				<td><%= link_to "Edit", edit_book_path(book, page: params[:page])%></td>
				<td><button class="delete"><%= link_to "Delete", book_path(book, page: params[:page]), method: :delete, remote: true%></button></td>
			<%end%>
		</tr>
		<%end%>
	</tbody>
</table>
<%if current_user%>
	<%= link_to "New book", new_book_path%>
<%end%>
<br>
<%= paginate @books %>
<br>

app/views/books/like.js.erb
	// <% if current_user.liked_book?(@book)%>
	// 	$(".like input[type=submit]").val("Unlike")
	// <% else %>
	// 	$(".like input[type=submit]").val("Like")
	// <%end%>
	// console.log("hello")

$(".like").html("<%= j render partial:'like'%>")

app/views/books/new.html.erb
<%= form_for @book do |b|%>
	<%= render partial: 'form', locals: {b: b}%>
<%end%>

app/views/books/profile.html.erb
<h3>This is <%= @user.first_name %> <%= @user.last_name %>'s profile</h3>

app/views/books/schedule.js.erb
alert("hello")
// $("#new_book").find(".submit").remove()
// $("#new_book").append("<%= b.submit "schedule"%>")
// $("#new_book").append("<%= b.text_field :onshelf_day%>")
$(".schedule input[value=schedule]").remove("input[value=schedule]").append('<%=j render partial: 'schedule' %>')

app/views/books/show.html.erb
<h3>Book name: <%= @book.name%></h3>

<%if current_user%>
	<div class="collect">
			<%if !current_user.collected_books.exists?(@book)%>
				<%=button_to "collection", collection_book_path(@book), remote: true%>
			<%else%>
				<h3 style="color:blue">Book collected</h3>
			<%end%>
	</div>
	<div class="like">
		<%= render partial: 'like', locols: {book: @book}%>
		<!--<% if current_user.liked_book?(@book)%>
			<%= button_to "Unlike", like_book_path(@book), remote: true%>
		<% else %>
			<%= button_to "Like", like_book_path(@book), remote: true%>
		<%end%>-->
	</div>
<%end%>


<h3>Book description: <%= @book.description%></h3>
<h3>Book On_shelf day: <%= @book.onshelf_day%></h3>
<h3>Aurthor name: <%= @book.user.short_name%></h3>
<h3>Group name: </h3>
<h3>Photo: <%= image_tag(@book.logo.url(:medium))%></h3>
<% @book.groups.each do |bg|%>
	<h3><%= bg.name%></h3>
<%end%>
<% @book.tags.each do |tag|%>
	<h3><%= tag.name%></h3>
<%end%>

<h3>There are some comments for <%= @book.name%> below:</h3>
<%if current_user%>
	<%= form_for [@book, @comment], remote: true do |c|%>
		<%= c.file_field :logo%>
		<%if @comment.logo.exists?%>
			<%= c.label "Remove photo"%>
			<%= check_box_tag "remove_img", "1"%>
		<%end%>
		<%= c.label :description, "Comment"%>
		<%= c.text_area :description%>
		<%= hidden_field_tag :page, params[:page] %>
		<%= c.submit "draft"%>
		<%= c.submit%>
	<%end%>
<%end%>

<table class="table table-striped">
	<thead>
		<tr>
			<th>Photo</th>
			<th>Name</th>
			<th>Comment</th>
			<%if current_user%>
				<th>Edit</th>
				<th>Delete</th>
			<%end%>
		</tr>
	</thead>
	<tbody class="comment">
		<% @comments.each do |c|%>
		<tr>	
			<%if c.logo.exists?%>
				<td><%= image_tag(c.logo.url(:thumb) )%></td>
			<%else%>
				<td>None</td>
			<%end%>		
			<td><%= c.user.short_name%></td>
			<td><%= c.description%></td>
			<%if current_user && current_user == c.user%>
				<td><%= link_to "Edit", book_path(@book, eid: c.id)%></td>
				<td><button class="delete"><%= link_to "Delete", book_comment_path(@book, c, page: params[:page]), method: :delete, remote: true%></button></td>
				<!-- data: {confirm: "Are you sure?!!"}, -->
			<%end%>
		</tr>
		<%end%>
	</tbody>
</table>
	<%= paginate @comments %>
	<br>

<script>
	var csrfToken = $("head meta[name=csrf-token]").attr("content");
	
</script>

app/views/books/subscribe.js.erb
	<%if current_user.subscribed_books.exists?(@book.id)%>
		$(".subs a").on('ajax:success', function(e) {
		e.preventDefault();
        $(this).html("Unsubscribe")
});	  
	<%else%>
		$(".subs a").on('ajax:success', function(e) { 
		e.preventDefault();
        $(this).html("Subscribe")
});
	<%end%>
	console.log("hihi")