config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }

  resources :books do
  	resources :comments, controller: 'book_comments'
	
  	collection do
  	  get :about
  	  post :bulk_selectgroup
  	end

    member do
      post :collection
      post :like
      post :subscribe
      post :schedule
    end
  end



  resources :users 
  resources :friendships

  namespace :admin do
    resources :books
    resources :groups
    resources :users
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root "books#index"
end

app/models/group.rb
class Group < ApplicationRecord
	validates_presence_of :name

	has_many :book_groupships, :dependent => :destroy
	has_many :books, through: :book_groupships
end

app/controllers/admin/groups_controller.rb
class Admin::GroupsController < ApplicationController

	before_action :is_admin
	before_action :authenticate_user!
	before_action :find_group, except: [:index, :create]

	def index
		if params[:gid].present?
			@group = Group.find(params[:gid])
		else
			@group = Group.new
		end

		@groups = Group.all
	end

	def create
		@group = Group.new(set_params)
		@group.save
		redirect_to admin_groups_path
	end

	def update
		@group.update(set_params)
		redirect_to admin_groups_path
	end

	def destroy
		 if !@group.books.present?
		 	@group.destroy
		 	redirect_to admin_groups_path
		 else
			flash[:alert] = "This is not allowed!!!"
			redirect_to admin_groups_path
		 end
		
	end

	private

	def find_group
		@group = Group.find(params[:id])
	end

	def set_params
		params.require(:group).permit(:name)
	end

	def is_admin
      unless  current_user.role == "admin"
          redirect_to root_path
          return
      end
    end 
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController

end

app/helpers/admin/groups_helper.rb
module Admin::GroupsHelper
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/views/admin/groups/index.html.erb
<h1>Group class</h1>
<%= form_for @group, url: admin_groups_path do |g|%>
	<%= g.text_field :name%>
	<%= g.submit%>
<%end%>

<table class="table table-striped">
	<thead>
		<tr>
			<td>Groups</td>
			<td>Edit</td>
			<td>Delete</td>
		</tr>
	</thead>
		<tr>
		<%@groups.each do |group|%>
			<td><%= group.name%></td>
			<td><%= link_to "Edit name", admin_groups_path(gid: group.id )%></td>
			<td><%= link_to "Delete", admin_group_path(group), method: :delete, data: {confirm: "Please check this group is not to use."}%></td>
		</tr>
		<%end%>

</table>