config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }

  resources :books do
  	resources :comments, controller: 'book_comments'
	
  	collection do
  	  get :about
  	  post :bulk_selectgroup
  	end

    member do
      post :collection
      post :like
      post :subscribe
      post :schedule
    end
  end



  resources :users 
  resources :friendships

  namespace :admin do
    resources :books
    resources :groups
    resources :users
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root "books#index"
end

app/views/layouts/admin.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Forum</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="container">
      <div class="row">
        <div class="col-md-12">
          <% if current_user%>
              <h3> <%= link_to current_user.try(:short_name), user_path(current_user)%>, you are admin!!!!</h3>
            <%end%>
        	<p style="color: green"><%= flash[:notice] %></p>
          <p style="color: red"><%= flash[:alert] %></p>
          <%= yield %>
          <%= link_to "Editing groups for books ", admin_groups_path%>
          <br>
          <%= link_to "Users management ", admin_users_path%>
          <br>
          <%= link_to "Back to bookstore", books_path(page: params[:page])%>
        </div>
      </div>
    </div>
  </body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Forum</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

    
  </head>

  <body>
    <div class="container">
      <div class="row">
        <div class="col-md-12">
          <%= link_to "About us", about_books_path%>
          <br>
          <% if current_user%>
              <h3> <%= link_to current_user.try(:short_name), user_path(current_user)%>, you are in AC bookstore.</h3>
            <%end%>
        	<p style="color: green"><%= flash[:notice] %></p>
          <p style="color: red"><%= flash[:alert] %></p>

  	      <% if current_user %>
    		    <%= link_to('登出', destroy_user_session_path, :method => :delete) %> |
    		    <%= link_to('修改個人資料', edit_registration_path(:user)) %>
    		  <% else %>
    		    <%= link_to('註冊', new_registration_path(:user)) %> |
    		    <%= link_to('登入', new_session_path(:user)) %>
            <%= link_to "登入 Facebook", user_facebook_omniauth_authorize_path %>
    		  <% end %>
    		  
          <%= yield %>
          <%= link_to "Back to bookstore", books_path(page: params[:page])%>
          
          <%if current_user.present? && current_user.role == "admin"%>
          
            <%= link_to 'admin', admin_books_path%>
          <%end%>  
        </div>
      </div>
    </div>
  </body>
</html>